// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqoxiefmujrtixexhzbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxb3hpZWZtdWpydGl4ZXhoemJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NzM4NDMsImV4cCI6MjA2NjA0OTg0M30.hbTapyTWxcc79bt5Oa8Otwx12wWBJr6FEMH_fF2vICg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);